# Generated by Django 4.2.30 on 2026-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus_wing',
            field=models.CharField(blank=True, help_text='Campus wing / Location for filtering', max_length=100, null=True),
        ),
    ]
