# Generated by Django 4.2.30 on 2026-06-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_FAILED', 'Payment Failed'), ('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PRINTING', 'Printing'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('COLLECTED', 'Collected')], default='PENDING_PAYMENT', max_length=25)),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='BW', max_length=10)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('double_sided', models.BooleanField(default=False)),
                ('student_comment', models.TextField(blank=True, default='')),
                ('shop_rejection_reason', models.TextField(blank=True, null=True)),
                ('price_breakdown', models.JSONField(blank=True, default=dict, help_text='Snapshot of price calculation at order time')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('binding_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.bindingoption')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shops.shop')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=25, null=True)),
                ('to_status', models.CharField(max_length=25)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='order_files/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, help_text='Remote URL if using cloud storage')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='pdf, docx, jpg, png', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete for retention cleanup')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
            options={
                'db_table': 'order_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'status'], name='orders_shop_id_30d977_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student'], name='orders_student_4f4f01_idx'),
        ),
    ]
