# Generated by Django 4.2.30 on 2026-07-07 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_FAILED', 'Payment Failed'), ('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PRINTING', 'Printing'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('COLLECTED', 'Collected')], default='PLACED', max_length=25),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Itemized bill and parameters snapshot')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='orders.order')),
            ],
            options={
                'db_table': 'order_receipts',
                'ordering': ['-generated_at'],
            },
        ),
    ]
