# Generated by Django 4.2.30 on 2026-06-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, default='Indore', max_length=100)),
                ('area', models.CharField(default='Vijay Nagar', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HOLIDAY', 'Holiday')], default='CLOSED', max_length=10)),
                ('status_updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Super Admin must approve before shop is visible')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable by admin')),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'SHOP_OWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HOLIDAY', 'Holiday')], max_length=10)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shops.shop')),
            ],
            options={
                'db_table': 'shop_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bw_rate_per_page', models.DecimalField(decimal_places=2, help_text='Rate in INR per page for B&W', max_digits=8)),
                ('color_rate_per_page', models.DecimalField(decimal_places=2, help_text='Rate in INR per page for Color', max_digits=8)),
                ('double_sided_supported', models.BooleanField(default=True)),
                ('double_sided_rate_per_page', models.DecimalField(blank=True, decimal_places=2, help_text='If different from single-sided, otherwise uses same rate', max_digits=8, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='shops.shop')),
            ],
            options={
                'db_table': 'price_lists',
            },
        ),
        migrations.CreateModel(
            name='BindingOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Spiral Binding, Stapled, Hardcover', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Flat charge in INR', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_options', to='shops.shop')),
            ],
            options={
                'db_table': 'binding_options',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['city', 'status', 'is_approved'], name='shops_city_079e0c_idx'),
        ),
    ]
