# Generated by Django 4.2.30 on 2026-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='discount_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HOLIDAY', 'Holiday'), ('MAINTENANCE', 'Under Maintenance')], default='CLOSED', max_length=15),
        ),
        migrations.AlterField(
            model_name='shopstatuslog',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HOLIDAY', 'Holiday'), ('MAINTENANCE', 'Under Maintenance')], max_length=20),
        ),
    ]
